on:
  schedule:
    - cron: '5 * * * *' # Scheduled run at midnight every day
  push:
    branches:
      - main
      - dev

jobs:

  delete-azure-vms:
    name: Delete Azure VMs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, preprod, dev]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Delete Azure VMs
        if: (github.event_name == 'schedule') || (github.event_name == 'push' && github.ref == 'refs/heads/${{ matrix.branch }}')
        run: |
          echo "Deleting Azure VMs for branch: ${{ matrix.branch }}"
          # Steps to delete Azure VMs for the current branch
