on:
  schedule:
    - cron: '5 0 * * *' # Scheduled run at midnight every day
  push:
    branches:
      - main
      - dev

jobs:

  delete-azure-vms:
    name: Delete Azure VMs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Delete Azure VMs
        if: github.ref == 'refs/heads/${{ matrix.branch }}'
        run: |
          # Steps to delete Azure VMs for the current branch
          echo "Deleting Azure VMs for branch: ${{ matrix.branch }}"
