name: Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  cron_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print current time
      run: |
        date
        echo "This job runs every 5 minutes"
