on:
  schedule:
    - cron: '5 * * * *' # Scheduled run at midnight every day
  push:
    branches:
      - main
      - dev

jobs:

  delete-azure-vms:
    name: Delete Azure VMs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Delete Azure VMs
        if: github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/${{ github.event.ref_name }}')
        run: |
          echo "Deleting Azure VMs for branch: ${{ github.event.ref_name }}"
          # Steps to delete Azure VMs for the current branch
