name: Delete Azure VMs

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  delete-azure-vms:
    name: Delete Azure VMs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Delete Azure VMs
        if: github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/${{ github.event.ref_name }}')
        run: |
          echo "Deleting Azure VMs for branch: ${{ github.event.ref_name }}"
          
        
